# Generated by Django 4.2.7 on 2023-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='posts.tagmodel'),
        ),
    ]
