# Generated by Django 4.2.7 on 2023-11-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpostmodel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
