# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musiclibrary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likedcontentmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followmodel',
            name='artists',
            field=models.ManyToManyField(related_name='followers_of_artist', to='musiclibrary.artistmodel'),
        ),
        migrations.AddField(
            model_name='followmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followings_of_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albummodel',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_by_artist', to='musiclibrary.artistmodel'),
        ),
    ]
