# Generated by Django 4.2.7 on 2023-11-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/<django.db.models.fields.related.OneToOneField>/profile/'),
        ),
    ]
