# Generated by Django 4.2.7 on 2023-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='liked_albums', to='musiclibrary.albummodel'),
        ),
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='liked_playlists', to='musiclibrary.playlistmodel'),
        ),
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to='musiclibrary.songmodel'),
        ),
    ]
