# Generated by Django 4.2.7 on 2023-11-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0002_alter_createpostmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpostmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
