# Generated by Django 4.2.7 on 2023-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0003_alter_likedcontentmodel_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='liked', to='musiclibrary.albummodel'),
        ),
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='liked', to='musiclibrary.playlistmodel'),
        ),
        migrations.AlterField(
            model_name='likedcontentmodel',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='liked', to='musiclibrary.songmodel'),
        ),
    ]
