# Generated by Django 4.2.7 on 2023-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_artist',
        ),
    ]
