# Generated by Django 4.2.7 on 2023-11-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.CharField(help_text='Field is unique. You can register with this email only once', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='This image will be user as your profile picture', null=True, upload_to='photos/'),
        ),
    ]
