# Generated by Django 4.2.7 on 2023-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_alter_customusermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='This image will be used as your profile picture', null=True, upload_to='photos/'),
        ),
    ]
