# Generated by Django 4.2.7 on 2023-11-26 11:18

from django.db import migrations, models
import siteuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_alter_customusermodel_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_img',
            field=models.ImageField(blank=True, default='../assets/main/img/blank-pofile-picture.png', help_text='This image will be used as your profile picture.', null=True, upload_to=siteuser.models.CustomUserModel.user_directory_path),
        ),
    ]
